spring.application.name=libreria

#configuracion de conexion
spring.datasource.url=jdbc:mysql://localhost:3306/dbLibreria2useSSL=false&servertimezone=utc
spring.datasource.username=root
spring.datasource.password=root

#dialecto de MYSQL
#spring.jpadatabse-plataform=org.hibernate.dialect.MYSQL8Dialect

#Esquema
spring.jpa.hibernate.ddl-auto=update

#mostrar en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
